spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/foodfood
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

  deserialization:
    fail-on-unknown-properties: false # @JsonIgnoreProperties 프로젝트 전체 적용

jwt:
  token:
    secret: ${JWT_TOKEN_SECRET}  # 실제로 사용하는 비밀키는 환경변수로 로컬에 저장.(노출 방지)

# api 조회시 필요한 정보들(외부에 노출되서는 안되거나 변하지 않는값들)
openApi:
  baseUrl: ${OPEN_API_BASEURL}
  ServiceKey: ${OPEN_API_SERVICE_KEY}
  type: json