spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodfood_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 7721
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging:
  level:
    org.hibernate.SQL: debug
#  org.hibernate.type: trace

  deserialization:
    fail-on-unknown-properties: false # @JsonIgnoreProperties 프로젝트 전체 적용

jwt:
  token:
    secret: ${JWT_TOKEN_SECRET}  # 실제로 사용하는 비밀키는 환경변수로 로컬에 저장.(노출 방지)
    expireTimeMs: ${JWT_TOKEN_EXPIRE_TIME_MS}

oauth2:
  google:
    client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    redirect-uri: ${OAUTH2_GOOGLE_REDIERECT-URI}
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
  kakao:
    client-id: 클라이언트ID
    client-secret: 클라이언트SECRET
    redirect-uri: 리디렉션URI
    token-uri: 엑세스토큰URI
    resource-uri: 리소스URI

# api 조회시 필요한 정보들(외부에 노출되서는 안되거나 변하지 않는값들)
openApi:
  baseUrl: ${OPEN_API_BASEURL}
  ServiceKey: ${OPEN_API_SERVICE_KEY}
  type: json

