spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodfood_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 7721
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging:
  level:
    org.hibernate.SQL: debug
  #  org.hibernate.type: trace

  deserialization:
    fail-on-unknown-properties: false # @JsonIgnoreProperties 프로젝트 전체 적용

jwt:
  token:
    secret: ${JWT_TOKEN_SECRET}  # 실제로 사용하는 비밀키는 환경변수로 로컬에 저장.(노출 방지)
    expireAccessTokenTimeMs: ${JWT_TOKEN_EXPIRE_ACCESS_TOKEN_TIME_MS}
    expireRefreshTokenTimeMs: ${JWT_TOKEN_EXPIRE_REFRESH_TOKEN_TIME_MS}

oauth2:
  google:
    client-id: ${OAUTH2_GOOGLE_CLIENT-ID}
    client-secret: ${OAUTH2_GOOGLE_CLIENT-SECRET}
    redirect-uri: ${OAUTH2_GOOGLE_REDIRECT-URI}
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
  naver:
    client-id: _cv35E5G0b9mrWrqJwC5
    client-secret: fDhF9sOgQv
    redirect-uri: http://localhost:8080/login/oauth2/code/naver
    authorization-grant-type: authorization_code
    client-name: Naver
    scope: name, email

    kakao:
      client-id: 724dcc0d63d686d2a8ee1f43fbaaa2ae
      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
      client-authentication-method: POST
      authorization-grant-type: authorization_code
      client-name: Kakao
      scope: profile_nickname, profile_image, account_email

    provider:
      naver:
        authorization-uri: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        user-name-attribute: response

      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id


